export { default as EHeader } from './Header.vue'
export { default as EFooter } from './Footer.vue'
export { default as EAside } from './Aside.vue'
export { default as EMain } from './Main.vue'
export { default as ELayout } from './Layout.vue'
