export { default as Header } from './Header.vue'
export { default as Footer } from './Footer.vue'
export { default as Aside } from './Aside.vue'
export { default as Main } from './Main.vue'
export { default as Layout } from './Layout.vue'
